### ISSUE TITLE
Connection timed out 2016

### ISSUE THREAD

**Issue by mRokita** [Grycek/ChomikUploader#12]
``` python
Traceback (most recent call last):
  File "./chomik", line 9, in <module>
    import src.main
  File "/home/mrokita/ChomikUploader/src/main.py", line 71, in <module>
    u = uploader.Uploader(login, password, debug = debug)
  File "/home/mrokita/ChomikUploader/src/uploader.py", line 84, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/home/mrokita/ChomikUploader/src/chomikbox.py", line 200, in login
    if self.relogin() == True:
  File "/home/mrokita/ChomikUploader/src/chomikbox.py", line 227, in relogin
    resp = self.send(header)
  File "/home/mrokita/ChomikUploader/src/chomikbox.py", line 185, in send
    tmp = sock.recv(640) 
socket.timeout: timed out
```

**Comment by Grycek** [comment]
Być może chomikuj.pl zmieniło protokół. Muszę to przejrzeć. 
Też zauważyłem, że w moim programie przestała działać możliwość logowania się z polskimi hasłami.
