### ISSUE TITLE
Logowanie - błąd

### ISSUE THREAD

**Issue by replay111** [Grycek/ChomikUploader#14]
Witam,

świeża sprawa - jakoś po tym weekendzie przestało działać:

```
Logowanie
Traceback (most recent call last):
  File "/usr/bin/chomik", line 6, in <module>
    import chomikuploader.main
  File "/usr/lib/python2.7/site-packages/chomikuploader/main.py", line 64, in <module>
    u = uploader.Uploader(login, password, debug = debug)
  File "/usr/lib/python2.7/site-packages/chomikuploader/uploader.py", line 84, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/usr/lib/python2.7/site-packages/chomikuploader/chomikbox.py", line 200, in login
    if self.relogin() == True:
  File "/usr/lib/python2.7/site-packages/chomikuploader/chomikbox.py", line 227, in relogin
    resp = self.send(header)
  File "/usr/lib/python2.7/site-packages/chomikuploader/chomikbox.py", line 185, in send
    tmp = sock.recv(640)
socket.timeout: timed out
```

BTW - jest gdzieś na necie jakaś dokumentacja tego API - czy sam rozpoznawałeś jak to działa?

**Comment by Grycek** [comment]
Odnośnie API - to był reverse engineering w moim wykonaniu.

Co do logowania to próbuję odkryć gdzie jest problem. API wydaje mi się, że się nie zmieniło.

**Comment by Grycek** [comment]
Chyba już naprawiłem w nowej wersji, ale nie miałem okazji za dużo potestować.

**Comment by darkstormfwm** [comment]
Siemasz Grycek

A można poprosić jeszcze w downloaderze o poprawkę ?

Pozdrawiam

**Comment by replay111** [comment]
Nadal to samo:

```
Logowanie
Traceback (most recent call last):
  File "/usr/bin/chomik", line 6, in <module>
    import chomikuploader.main
  File "/usr/lib/python2.7/site-packages/chomikuploader/main.py", line 64, in <module>
    u = uploader.Uploader(login, password, debug = debug)
  File "/usr/lib/python2.7/site-packages/chomikuploader/uploader.py", line 84, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/usr/lib/python2.7/site-packages/chomikuploader/chomikbox.py", line 203, in login
    self.get_dir_list()
  File "/usr/lib/python2.7/site-packages/chomikuploader/chomikbox.py", line 272, in get_dir_list
    resp_dict =  self.soap.soap_xml_to_dict(resp)
  File "/usr/lib/python2.7/site-packages/chomikuploader/soap.py", line 12, in soap_xml_to_dict
    return parse(xml)
  File "/usr/lib/python2.7/site-packages/chomikuploader/soap.py", line 178, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 25
```

Wykonałem ```git pull --all```
i potem ponownie ``` sudo python setup.py install ``` 

System: Centos 7.x / Python 2.7.5

**Comment by Grycek** [comment]
Kolejna próba.
A teraz jak działa?

**Comment by replay111** [comment]
U mnie działa!

**Comment by darkstormfwm** [comment]
U mnie nadal lipa ;)

Logowanie
Traceback (most recent call last):
  File "/usr/local/bin/chomik", line 6, in <module>
    import chomikuploader.main
  File "/usr/local/lib/python2.7/dist-packages/chomikuploader/main.py", line 64, in <module>
    u = uploader.Uploader(login, password, debug = debug)
  File "/usr/local/lib/python2.7/dist-packages/chomikuploader/uploader.py", line 84, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/usr/local/lib/python2.7/dist-packages/chomikuploader/chomikbox.py", line 208, in login
    self.get_dir_list()
  File "/usr/local/lib/python2.7/dist-packages/chomikuploader/chomikbox.py", line 277, in get_dir_list
    resp_dict =  self.soap.soap_xml_to_dict(resp)
  File "/usr/local/lib/python2.7/dist-packages/chomikuploader/soap.py", line 12, in soap_xml_to_dict
    return parse(xml)
  File "/usr/local/lib/python2.7/dist-packages/chomikuploader/soap.py", line 178, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 2, column 0

**Comment by replay111** [comment]
A ściągałeś coś w międzyczasie chomikboxem?

**Comment by darkstormfwm** [comment]
Nie nie mam nawet zainstalowanego

**Comment by replay111** [comment]
No ja teraz dla próby pobrałem sobie plik z konta i zrobiłem upload (z nowej wersji skryptów)

**Comment by darkstormfwm** [comment]
Nic ja będę musiał poczekać aż szef obada o co biega :smi 
Potem muszę mu sprezentować jaką fajną flaszkę za świetną robotę :+1:

**Comment by replay111** [comment]
Ja musz obczaić ten kod - nie znam pythong-a ale fajnie to to działa ;-)

**Comment by darkstormfwm** [comment]
Ja liczę że kiedyś też downloader będzie śmigać bo w sumie też z niego sporo korzystam równolegle do uploadera 
A świetnie działa jak się skrypcik napisze i upie i ściąga co potrzeba z chomiczka :smile:

**Comment by Grycek** [comment]
Mam pewne podejrzenie gdzie jest problem. Kod pisałem dość dawno i pewnie teraz bym napisał to inaczej.

Ogólnie całą wymianę pakietów robię na poziomie socketów. Zauważyłem, że chomikuj w protokole od chomikboksa ostatnio zaczął dodawać jakieś śmieci na początku lub końcu pakietu. Dodatkowo jeżeli pakiet jest duży, to śmieci zdarzają się też wewnątrz pakietu.
Przy logowaniu jest pobierane drzewo katalogów z chomikuj. Jeżeli ktoś na swoim koncie ma dużo katalogów, to mogą się pojawić śmieci w pakiecie i nie można wtedy sparsować XML'a.

Prawdopodobnie gdybym korzystał z jakiejś biblioteki do obsługi pakietów http (bo tym jest protokół chomikboksa), to biblioteka sama zajmowałaby się tymi śmieciami. Spróbuję to przetestować, ale prawdopodobnie dopiero w weekend.

**Comment by darkstormfwm** [comment]
Czyli utrudniają życie, plików sporo jest katalogów w sumie też :smile: 
Życzę powodzenia z tym ustrojstwem ja sobie pliczki na razie poodkładam do uploadu na później.

**Comment by KarwaszTwarz** [comment]
```
Traceback (most recent call last):
  File "/root/chomik/chomik", line 9, in <module>
    import src.main
  File "/root/chomik/src/main.py", line 71, in <module>
    u = uploader.Uploader(login, password, debug = debug)
  File "/root/chomik/src/uploader.py", line 84, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/root/chomik/src/chomikbox.py", line 208, in login
    self.get_dir_list()
  File "/root/chomik/src/chomikbox.py", line 277, in get_dir_list
    resp_dict =  self.soap.soap_xml_to_dict(resp)
  File "/root/chomik/src/soap.py", line 12, in soap_xml_to_dict
    return parse(xml)
  File "/root/chomik/src/soap.py", line 178, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 131068
```
Niestety, musimy poczekać na lepsze czasy :)

**Comment by Grycek** [comment]
Kolejna próba - może teraz zadziała. Nie aktualizowałem paczek. Jeżeli ktoś chce przetestować musi ściągnąć kod.

**Comment by darkstormfwm** [comment]
U mnie działa wersja z SRC , Teraz tylko do szczęścia potrzebny mi downloader :dagger:

**Comment by replay111** [comment]
Faktycznie - przestało działać, po aktualizacji źródeł i ponownym odpaleniu jest ok :D

**Comment by Grycek** [comment]
Dodałem paczki i zaktualizowałem ChomikDownloader'a.
