### ISSUE TITLE
Zawiecha na Logowanie

### ISSUE THREAD

**Issue by jcospawa** [Grycek/ChomikUploader#17]
Podaj haslo:

Logowanie
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    u = uploader.Uploader(login, password, debug = debug)
  File "/home/jcospawa/chomikUploader-0.5.4/src/uploader.py", line 84, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/home/jcospawa/chomikUploader-0.5.4/src/chomikbox.py", line 203, in login
    self.get_dir_list()
  File "/home/jcospawa/chomikUploader-0.5.4/src/chomikbox.py", line 272, in get_dir_list
    resp_dict =  self.soap.soap_xml_to_dict(resp)
  File "/home/jcospawa/chomikUploader-0.5.4/src/soap.py", line 12, in soap_xml_to_dict
    return parse(xml)
  File "/home/jcospawa/chomikUploader-0.5.4/src/soap.py", line 178, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: junk after document element: line 1, column 26

**Comment by Grycek** [comment]
Spróbuj chomikUploader-0.5.4.3.zip w katalogu dist

**Comment by jcospawa** [comment]
dzieki, dziala bez zarzutow :D
