### ISSUE TITLE
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 1

### ISSUE THREAD

**Issue by yoshibz** [Grycek/ChomikUploader#18]
[root@host ChomikUploader-master]# python2 chomik -u "/YYY/" "/XYZ/int.txt"
Podaj nazwe uzytkownika:
user
Podaj haslo:

Logowanie
Traceback (most recent call last):
  File "chomik", line 9, in <module>
    import src.main
  File "/aaaa/ChomikUploader-master/src/main.py", line 71, in <module>
    u = uploader.Uploader(login, password, debug = debug)
  File "/aaaa/ChomikUploader-master/src/uploader.py", line 84, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/aaaa/ChomikUploader-master/src/chomikbox.py", line 203, in login
    self.get_dir_list()
  File "/aaaa/ChomikUploader-master/src/chomikbox.py", line 272, in get_dir_list
    resp_dict =  self.soap.soap_xml_to_dict(resp)
  File "/aaaa/ChomikUploader-master/src/soap.py", line 12, in soap_xml_to_dict
    return parse(xml)
  File "/aaaa/ChomikUploader-master/src/soap.py", line 178, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 1

obojetne czy parametr -u czy -r ten sam problem.

**Comment by Grycek** [comment]
Z której wersji programu korzystasz?
Ten błąd teoretycznie powinien być już naprawiony w wersji chomikUploader-0.5.4.3
